[package]
name = "rhiaqey-hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = "debuginfo"
overflow-checks = true
panic = "abort"

[dependencies]
rhiaqey-sdk = { git = "https://github.com/rhiaqey/sdk.git" }
rhiaqey-common = { git = "https://github.com/rhiaqey/common.git" }
fred = { version="6.0.0-beta.2", features=[
    "dns",
    "blocking-encoding",
    "metrics",
    "sentinel-client",
    "subscriber-client",
    "serde-json"
] }
tokio = { version = "1", features = ["full"] }
axum = "0.6.4"
