apiVersion: v1
kind: Service
metadata:
  name: {{ include "rhiaqey-hub.fullname" . }}
  labels:
    {{- include "rhiaqey-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-private
      protocol: TCP
      name: http-private
    - port: {{ .Values.service.publicPort }}
      targetPort: http-public
      protocol: TCP
      name: http-public
  selector:
    {{- include "rhiaqey-hub.selectorLabels" . | nindent 4 }}
