name: Commit

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker builds setup
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: cargo build --all-features

      - name: Run tests
        run: cargo test --all-features

      # Get short git commit hash
      - name: Set up commit hash
        run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build docker image for hub
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          build-args: |
            BINARY=rhiaqey-hub
            GIT_COMMIT=${{ env.GIT_COMMIT }}
